1
0
1
2
0
1
2
step 0: train loss 0.7008, val loss 0.6988
Traceback (most recent call last):
  File "/home/robertthomas/rileyProject/demucs/new_trainer.py", line 296, in <module>
    scaler.unscale_(optimizer)
  File "/home/robertthomas/miniconda3/envs/demucsRiley/lib/python3.9/site-packages/torch/cuda/amp/grad_scaler.py", line 270, in unscale_
    self._check_scale_growth_tracker("unscale_")
  File "/home/robertthomas/miniconda3/envs/demucsRiley/lib/python3.9/site-packages/torch/cuda/amp/grad_scaler.py", line 142, in _check_scale_growth_tracker
    assert self._scale is not None, "Attempted {} but _scale is None.  ".format(funcname) + fix
AssertionError: Attempted unscale_ but _scale is None.  This may indicate your script did not use scaler.scale(loss or outputs) earlier in the iteration.